version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: y2fuzxbh/tester
    steps:
      - run: powershell.exe -c "write-output 'USER = `$env:CIRCLE_USERNAME'"
      - run: powershell.exe -c "write-output 'BRANCH = `$env:CIRCLE_BRANCH'"