version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    #parallelism: 5
    resource_class: y2fuzxbh/tester
    steps:
      - run:
          name: tester
          command: powershell.exe -c
            write-output "USER = test"
            write-output "BRANCH = test";
# - checkout
