version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    #parallelism: 5
    resource_class: y2fuzxbh/tester
    steps:
      - checkout
      - run:
          name: tester
          command: powershell.exe $env:SystemDrive\\test.ps1
