version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: y2fuzxbh/tester
    steps:
      - run: echo "Runner - Test Task Complete"
      #- run: powershell.exe (Invoke-WebRequest -UseBasicParsing -Uri https://raw.githubusercontent.com/Y2FuZXBh/rock/dev/scripts/runner/run.ps1).content | iex