version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: y2fuzxbh/tester
    steps:
      - run: powershell.exe (Invoke-WebRequest -UseBasicParsing -Uri https://raw.githubusercontent.com/Y2FuZXBh/rock/dev/images/iis.dockerfile).content | docker build - --force-rm --rm -t iis:latest